#!/usr/bin/env python3
"""
Generate TypeScript types from Pydantic models via FastAPI OpenAPI schema.

This script generates FastAPI's OpenAPI schema and converts it to TypeScript
types using openapi-typescript.
"""

import json
import subprocess
import sys
from pathlib import Path

# Paths
BACKEND_DIR = Path(__file__).parent.parent
FRONTEND_DIR = BACKEND_DIR.parent / "frontend"
OPENAPI_FILE = BACKEND_DIR / "openapi.json"
OUTPUT_FILE = FRONTEND_DIR / "src" / "lib" / "generated-types.ts"


def generate_openapi_schema():
    """Generate OpenAPI schema from FastAPI application."""
    print("🔄 Step 1: Generating OpenAPI schema from FastAPI...")

    # Import FastAPI app and generate schema
    app_dir = BACKEND_DIR / "app"
    sys.path.insert(0, str(app_dir))

    try:
        from main import app

        # Get OpenAPI schema from FastAPI
        openapi_schema = app.openapi()

        # Write schema to file
        OPENAPI_FILE.write_text(json.dumps(openapi_schema, indent=2))
        print(f"   ✅ OpenAPI schema generated: {OPENAPI_FILE}")

    except Exception as e:
        print(f"❌ Error generating OpenAPI schema: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


def generate_typescript_types():
    """Generate TypeScript types from OpenAPI schema."""
    print("🔄 Step 2: Converting OpenAPI schema to TypeScript...")
    print(f"   Input: {OPENAPI_FILE}")
    print(f"   Output: {OUTPUT_FILE}")

    try:
        # Generate TypeScript types using openapi-typescript
        result = subprocess.run(
            [
                "npx",
                "openapi-typescript",
                str(OPENAPI_FILE),
                "-o",
                str(OUTPUT_FILE),
            ],
            cwd=FRONTEND_DIR,
            capture_output=True,
            text=True,
        )

        if result.returncode != 0:
            print(f"❌ Error generating TypeScript types:")
            print(result.stderr)
            # Clean up OpenAPI file
            OPENAPI_FILE.unlink(missing_ok=True)
            sys.exit(1)

        print("✅ TypeScript types generated successfully!")
        print(f"   Generated file: {OUTPUT_FILE}")

        # Add header comment
        add_header_comment()

        # Clean up OpenAPI file
        OPENAPI_FILE.unlink(missing_ok=True)

        return True

    except FileNotFoundError:
        print("❌ Error: npx/openapi-typescript not found. Install it with:")
        print("   cd frontend && npm install --save-dev openapi-typescript")
        OPENAPI_FILE.unlink(missing_ok=True)
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error: {e}")
        OPENAPI_FILE.unlink(missing_ok=True)
        sys.exit(1)


def add_header_comment():
    """Add a header comment to the generated file."""
    header = """/**
 * AUTO-GENERATED TypeScript types from Pydantic models.
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is automatically generated from backend/app/api/models.py
 * Run `npm run generate-types` to regenerate.
 *
 * Source: backend/app/api/models.py
 * Generator: datamodel-code-generator
 */

"""

    content = OUTPUT_FILE.read_text()
    OUTPUT_FILE.write_text(header + content)


if __name__ == "__main__":
    generate_openapi_schema()
    generate_typescript_types()
    print("\n✨ Type generation complete! ✨")
    print("   The generated types are in sync with your Pydantic models.")
    print("   Import them in your frontend with:")
    print("   import type { paths, components } from '@/lib/generated-types'")
