#!/bin/bash
# Generate TypeScript types from FastAPI OpenAPI schema
#
# This script extracts the OpenAPI schema from the running FastAPI server
# and converts it to TypeScript types using openapi-typescript.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"
FRONTEND_DIR="$BACKEND_DIR/../frontend"
OPENAPI_FILE="$BACKEND_DIR/openapi.json"
OUTPUT_FILE="$FRONTEND_DIR/src/lib/generated-types.ts"

echo "🔄 Generating TypeScript types from Pydantic models..."
echo ""

# Step 1: Extract OpenAPI schema using FastAPI's built-in command
echo "Step 1: Extracting OpenAPI schema from FastAPI..."
cd "$BACKEND_DIR"

# Use uv run python to extract the schema with proper dependencies
uv run python << 'EOF'
import sys
import json
from pathlib import Path

# Add app directory to path
app_path = Path.cwd() / "app"
sys.path.insert(0, str(app_path))

try:
    from main import app

    # Get OpenAPI schema
    schema = app.openapi()

    # Write to file
    output_path = Path.cwd() / "openapi.json"
    with open(output_path, 'w') as f:
        json.dump(schema, f, indent=2)

    print(f"✅ OpenAPI schema generated: {output_path}")
    sys.exit(0)
except Exception as e:
    print(f"❌ Error: {e}", file=sys.stderr)
    import traceback
    traceback.print_exc()
    sys.exit(1)
EOF

if [ $? -ne 0 ]; then
    echo "❌ Failed to generate OpenAPI schema"
    exit 1
fi

# Step 2: Convert to TypeScript using openapi-typescript
echo ""
echo "Step 2: Converting OpenAPI schema to TypeScript..."
cd "$FRONTEND_DIR"

npx openapi-typescript "$OPENAPI_FILE" -o "$OUTPUT_FILE"

if [ $? -ne 0 ]; then
    echo "❌ Failed to convert to TypeScript"
    rm -f "$OPENAPI_FILE"
    exit 1
fi

# Step 3: Add header comment
echo ""
echo "Step 3: Adding header comment..."
TEMP_FILE="$OUTPUT_FILE.tmp"
cat > "$TEMP_FILE" << 'HEADER'
/**
 * AUTO-GENERATED TypeScript types from Pydantic models.
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is automatically generated from backend/app/api/models.py
 * Run `npm run generate-types` to regenerate.
 *
 * Source: backend/app/api/models.py via FastAPI OpenAPI schema
 * Generator: openapi-typescript
 */

HEADER

cat "$OUTPUT_FILE" >> "$TEMP_FILE"
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Clean up
rm -f "$OPENAPI_FILE"

echo ""
echo "✨ Type generation complete! ✨"
echo "   Generated file: $OUTPUT_FILE"
echo ""
echo "   The generated types are in sync with your Pydantic models."
echo "   Import them in your frontend with:"
echo "   import type { paths, components } from '@/lib/generated-types'"
